server:
  port: 9000
spring:
  application:
    name: exchange-rate
  main:
    banner-mode: off
app:
  timezone: UTC # OpenExchangeRates uses UTC
open-exchange-rates:
  url: "https://openexchangerates.org"
  app-id: ${OER_TOKEN}
  base-currency: USD
giphy:
  url: "https://api.giphy.com"
  api-key: ${GIPHY_TOKEN}
  rating: g # Use one of: y, g, pg, pg-13, r, unrated, nsfw, [empty]
giphy-media:
  url: "https://i.giphy.com"